name: Minimal Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup and Make
      run: |
        sudo apt-get update
        # ⚠️ 这里新增了 liblzma-dev 以支持编译 C 版本的 extractfv
        sudo apt-get install -y build-essential gcc-aarch64-linux-gnu clang lld llvm xxd python3 zip uuid-dev liblzma-dev
        
        # 执行默认的编译和打包步骤
        make dist DIST_NAME=canoe_release_build || true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: canoe-release-package
        path: release/canoe_release_build.zip
